inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# Support both, Ruby 1.9 hashmap and hash-rocket syntax
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

# disabled until we can configure "+" as concat sign
Style/LineEndConcatenation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 1

#Allow both ['a', 'b'], %w[a b] and %w(a b) style arrays
Style/WordArray:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/OptionalBooleanParameter:
  Enabled: false
